services:
  hosted-kcc:
    image: ghcr.io/lk4d4/hosted_kcc:latest
    container_name: hosted-kcc
    restart: unless-stopped
    environment:
      TZ: Europe/Zurich
    volumes:
      - ./data:/data
      - /volume1/data/media/manga/mangas:/input:ro
      - /volume1/docker/suwayomi/local:/output
    security_opt:
      - no-new-privileges:true
